apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-action-deployment
  labels:
    app: git-action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-action
  template:
    metadata:
      labels:
        app: git-action 
    spec:
      containers:
      - name: git-action
        image: djilanick1/git-action:main
        ports:
        - containerPort: 16000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: git-action-service
spec:
  selector:
    app: git-action 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 16000
    nodePort: 30110
